# build environment
FROM node:11.4.0 as builder
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json
RUN npm install --silent
RUN npm install v8 -- silent
RUN npm install react-scripts@1.1.1 -g --silent
RUN npm install awsmobile-cli --silent
RUN npm install aws-amplify aws-amplify-react --silent
RUN awsmobile init 
COPY . /usr/src/app
RUN npm run build



# production environment
FROM nginx:1.13.9-alpine
RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]